---
- name: Setup CI/CD Server
  hosts: all
  become: yes

  tasks:
    - name: Update apt and install dependencies
      apt:
        update_cache: yes
        name:
          - ca-certificates
          - curl
          - software-properties-common
        state: present

    - name: Install Docker
      apt:
        name: docker.io
        state: present
        update_cache: yes

    - name: Install Docker Compose plugin
      apt:
        name: docker-compose-plugin
        state: present

    - name: Ensure Docker is started
      service:
        name: docker
        state: started
        enabled: yes

    - name: Add user to docker group
      user:
        name: "{{ ansible_user }}"
        groups: docker
        append: yes